                                                                                                                                                              
 title: "Messages from the Universe"
theme: minima
github_username: "Astromiah"
minimal_mistakes_skin: neon
search: true
paginate: 5
remote_theme: mmistakes/minimal-mistakes

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
 - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Astromiah"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Insights, Reflections and Epiphanies on my journey through Physics"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://astromiah.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/astromiah"



footer:
  links: 
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/astromiah" 
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://astromiah.github.io"
  copyright: "ⓒ 2025 Astromiah. All Rights Reserved."

  
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      
# _pages
- scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /topics/
tag_archive:
  type: liquid
  path: /tags/

